import turtle
turtle.setup(650,350,200,200)
#turtle.penup()
turtle.fd(-250)
#turtle.pendown()
turtle.pensize(25)
turtle.pencolor("violet")
turtle.seth(-40)
for i in range(4):
    turtle.pencolor("purple")
    turtle.circle(40,80)
    turtle.pencolor("violet")
    turtle.circle(-40,80)
turtle.pencolor("red")
turtle.circle(40,80/2)
turtle.pencolor("purple")
turtle.fd(40)
turtle.pencolor("red")
turtle.circle(16,180)
turtle.pencolor("violet")
turtle.fd(40*2/3)
